# Generated by Django 4.2 on 2024-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
        ("users", "0002_userfollow_user_following_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="listens",
            field=models.ManyToManyField(
                related_name="user_who_listen", to="songs.song"
            ),
        ),
    ]
