# Generated by Django 4.2 on 2024-04-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_listens"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("user_from", "user_to")},
        ),
    ]
