# Generated by Django 4.2 on 2024-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_alter_song_likes"),
        ("users", "0004_alter_userfollow_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="listens",
            field=models.ManyToManyField(
                blank=True, related_name="user_who_listen", to="songs.song"
            ),
        ),
    ]
