# Generated by Django 4.2 on 2024-04-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_alter_playlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistsong",
            name="playlist",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_songs",
                to="playlists.playlist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(
                related_name="playlist_songs", to="playlists.playlistsong"
            ),
        ),
    ]
