# Generated by Django 4.2 on 2024-03-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_usersonglike_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersonglike',
            name='liked_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
            preserve_default=False,
        ),
    ]
