# Generated by Django 4.2 on 2024-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_usersonglike_liked_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="likes",
            field=models.ManyToManyField(blank=True, to="songs.usersonglike"),
        ),
    ]
