# Generated by Django 4.2 on 2024-05-02 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0004_alter_song_likes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersonglike",
            unique_together={("user", "liked_song")},
        ),
    ]
