# Generated by Django 4.2 on 2024-02-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lyric',
            name='language',
            field=models.CharField(choices=[('RU', 'Ru'), ('EN', 'En')], max_length=2),
        ),
        migrations.CreateModel(
            name='LyricLineTimecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecode', models.DurationField()),
                ('text_line', models.CharField(max_length=128)),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
    ]
