# Generated by Django 4.2 on 2024-04-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_usersonglike_liked_song"),
        ("lyrics", "0002_lyric_song_alter_lyric_language_lyriclinetimecode"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lyric",
            unique_together={("language", "song")},
        ),
    ]
